spring:
  web:
    resources:
      cache:
        period: 0
      static-locations: "file:F:/iCET/Individual Project/images"

  datasource:
    url: jdbc:mysql://localhost:3306/paperledge_db
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

